package fakehelper_test

import (
	"encoding/base64"
	"testing"
	"github.com/stretchr/testify/require"

	"github.com/amplify-cms/sys-share/sys-core/service/fakehelper"
)

func TestGenFakeLogoBytes(t *testing.T) {
	f, err := fakehelper.GenFakeLogoBytes(128)
	require.NoError(t, err)
	require.NotEqual(t, nil, f)
	t.Logf("Generated Bytes: %v", f)
	b64 := base64.RawStdEncoding.EncodeToString(f)
	t.Logf("Generated bytes in base64: %s", b64)
}

